[tool.poetry]
name = "csa-erp-client"
version = "0.1.0"
description = "A simple python client to access CSA ERP via ERPNext API"
authors = ["Radhakrishna Sanka <rkrishnasanka@gmail.com>"]
readme = "README.md"
packages = [{ include = "erp_client" }]


[tool.poetry.dependencies]
python = ">=3.10,<4.0"
requests = "^2.32.3"
pandas = "^2.2.2"
pymongo = "^4.11.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
ruff = "^0.9.9"
mypy = "^1.15.0"
types-requests = "^2.32.0.20241016"
pandas-stubs = "^2.2.3.241126"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
